import { useEffect, useState } from 'react'
import type { ComponentType } from 'react'
import { Link, NavLink, useNavigate } from 'react-router-dom'
import { Archive, BarChart3, Bell, BookOpen, Boxes, ClipboardCheck, Command, FileCheck2, Gavel, GitBranch, LayoutDashboard, LogOut, Menu, Moon, Search, Settings2, ShieldAlert, Sun, X } from 'lucide-react'
import { Logo } from './Logo'
import { logout } from '../lib/api'
import type { User } from '../types'

type NavItem = { to: string; label: string; icon: ComponentType<{size?: number}> }
const mainNav: NavItem[] = [
  {to:'/app',label:'Overview',icon:LayoutDashboard}, {to:'/app/submissions',label:'Submissions',icon:Boxes},
  {to:'/app/judging',label:'Judging',icon:Gavel}, {to:'/app/normalization',label:'Normalization',icon:BarChart3},
  {to:'/app/integrity',label:'Integrity',icon:ShieldAlert}, {to:'/app/audit',label:'Audit explorer',icon:GitBranch},
  {to:'/app/results',label:'Results',icon:FileCheck2}, {to:'/app/gallery',label:'Public gallery',icon:Archive}
]
type PaletteCommand = [string, string, ComponentType<{size?: number}>]

export function Shell({user,children}:{user:User;children:React.ReactNode}) {
  const [open,setOpen]=useState(false); const [dark,setDark]=useState(localStorage.getItem('trustforge.theme')!=='light'); const [palette,setPalette]=useState(false); const navigate=useNavigate()
  useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('trustforge.theme',dark?'dark':'light')},[dark])
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[])
  const signOut=async()=>{await logout();navigate('/')}
  return <div className="shell"><aside className={`sidebar ${open?'open':''}`}><div className="sidebar-top"><Link to="/" className="brand-link"><Logo/></Link><button className="mobile-close" onClick={()=>setOpen(false)}><X size={18}/></button></div><div className="event-switcher"><div className="event-dot"/><div><div className="event-name">TrustForge Demo</div><div className="muted tiny">Hackathon Raptors · 2026</div></div><span className="chevron">⌄</span></div><nav><div className="nav-label">Workspace</div>{mainNav.map(item=>{const Icon=item.icon;return <NavLink key={item.to} end={item.to==='/app'} to={item.to} onClick={()=>setOpen(false)} className={({isActive})=>`nav-item ${isActive?'active':''}`}><Icon size={17}/><span>{item.label}</span>{item.label==='Integrity'&&<span className="nav-pulse"/>}</NavLink>})}<div className="nav-label space-top">Manage</div><NavLink to="/app/judge" className={({isActive})=>`nav-item ${isActive?'active':''}`}><ClipboardCheck size={17}/><span>Judge workspace</span></NavLink><NavLink to="/app/certificate" className={({isActive})=>`nav-item ${isActive?'active':''}`}><BookOpen size={17}/><span>Certificate verify</span></NavLink></nav><div className="sidebar-bottom"><button className="nav-item" onClick={()=>setPalette(true)}><Command size={17}/><span>Command palette</span><kbd>⌘ K</kbd></button><button className="nav-item" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}<span>{dark?'Light mode':'Dark mode'}</span></button><div className="profile"><div className="avatar">{user.name.slice(0,1)}</div><div className="profile-copy"><strong>{user.name}</strong><span>{user.role.toLowerCase()}</span></div><button className="icon-button" title="Sign out" onClick={signOut}><LogOut size={16}/></button></div></div></aside><main className="main"><header className="topbar"><button className="mobile-menu" onClick={()=>setOpen(true)}><Menu size={20}/></button><div className="crumb"><span className="muted">Workspace</span><span>/</span><strong>{mainNav.find(n=>location.pathname===n.to||location.pathname.startsWith(n.to+'/'))?.label??'Control room'}</strong></div><div className="top-actions"><button className="search-button" onClick={()=>setPalette(true)}><Search size={16}/><span>Search anything…</span><kbd>⌘ K</kbd></button><button className="icon-button notification"><Bell size={17}/><i/></button><button className="icon-button"><Settings2 size={17}/></button></div></header><div className="page">{children}</div></main>{palette&&<CommandPalette close={()=>setPalette(false)} navigate={(path)=>{setPalette(false);navigate(path)}}/>}</div>
}
function CommandPalette({close,navigate}:{close:()=>void;navigate:(path:string)=>void}) { const commands:PaletteCommand[]=[['Overview','/app',LayoutDashboard],['Submissions','/app/submissions',Boxes],['Judging','/app/judging',Gavel],['Normalization','/app/normalization',BarChart3],['Judging Integrity','/app/integrity',ShieldAlert],['Audit explorer','/app/audit',GitBranch],['Verified results','/app/results',FileCheck2],['Public gallery','/app/gallery',Archive]];return <div className="modal-backdrop" onClick={close}><div className="palette" onClick={e=>e.stopPropagation()}><div className="palette-input"><Search size={18}/><input autoFocus placeholder="Search workspace…"/><kbd>ESC</kbd></div><div className="palette-label">Navigate to</div>{commands.map(([name,path,Icon])=><button className="palette-row" key={path} onClick={()=>navigate(path)}><span className="palette-icon"><Icon size={16}/></span><span>{name}</span><span className="muted shortcut">↵</span></button>)}</div></div> }
