import { useEffect, useState } from 'react'
import { Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { api, getAccess } from './lib/api'
import type { User } from './types'
import { Shell } from './components/Shell'
import Landing from './pages/Landing'
import Login from './pages/Login'
import Dashboard from './pages/Dashboard'
import Submissions from './pages/Submissions'
import Judging from './pages/Judging'
import Normalization from './pages/Normalization'
import Integrity from './pages/Integrity'
import Audit from './pages/Audit'
import Results from './pages/Results'
import Gallery from './pages/Gallery'
import JudgeWorkspace from './pages/JudgeWorkspace'
import Certificate from './pages/Certificate'

export default function App(){const [user,setUser]=useState<User|null>(null);const [loading,setLoading]=useState(Boolean(getAccess()));const navigate=useNavigate();useEffect(()=>{if(getAccess())api<User>('/api/v1/auth/me').then(setUser).catch(()=>setUser(null)).finally(()=>setLoading(false));else setLoading(false)},[]);if(loading)return <div className="splash"><div className="splash-logo">TF</div><span>Loading TrustForge…</span></div>;return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={user?<Navigate to="/app"/>:<Login onLogin={(next)=>{setUser(next);navigate('/app')}}/>}/><Route path="/app/*" element={user?<Shell user={user}><Routes><Route index element={<Dashboard/>}/><Route path="submissions" element={<Submissions/>}/><Route path="judging" element={<Judging/>}/><Route path="normalization" element={<Normalization/>}/><Route path="integrity" element={<Integrity/>}/><Route path="audit" element={<Audit/>}/><Route path="results" element={<Results/>}/><Route path="gallery" element={<Gallery user={user}/>} /><Route path="judge" element={<JudgeWorkspace/>}/><Route path="certificate" element={<Certificate/>}/><Route path="*" element={<Navigate to="/app"/>}/></Routes></Shell>:<Navigate to="/login"/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
